### ISSUE TITLE
Add New Mods

### ISSUE THREAD

**Issue by Pugemonster** [JohnTheCoolingFan/TBN3#1]
Add Actually Additions https://minecraft.curseforge.com/mc-mods/228404

**Comment by Pugemonster** [comment]
Add Open Blocks https://minecraft.curseforge.com/mc-mods/228816

**Comment by Pugemonster** [comment]
Add StepUP https://minecraft.curseforge.com/mc-mods/239236

**Comment by Pugemonster** [comment]
Add UniDict https://minecraft.curseforge.com/mc-mods/244258

**Comment by Pugemonster** [comment]
Add ItemScroller https://minecraft.curseforge.com/mc-mods/242064

**Comment by Pugemonster** [comment]
Add Fast Leaf Decay https://minecraft.curseforge.com/mc-mods/230976

**Comment by JohnTheCoolingFan** [comment]
Actually Additions - Added
OpenBlocks - Added
StepUP - Not added, this functionality is available in other mods that are present in this modpack
UniDict - Added
ItemScroller - Replaced by MouseTweaks
Fast Leaf Decay - Added
